import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import { ReduxProvider } from "@/components/providers/ReduxProvider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={` antialiased`}>
          <ReduxProvider >
            {children}
            <Toaster position="bottom-right" reverseOrder={false} />
          </ReduxProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
